gravitational/provisioner

Makefile
README.md
scripts/Makefile
scripts/terraform/asg.tf
scripts/terraform/base.tf
scripts/terraform/envvars.tf
scripts/terraform/iam.tf
scripts/terraform/instance.tf
scripts/terraform/node-user-data.tpl
scripts/terraform/sqs.tf
scripts/terraform/ssm.tf
scripts/terraform/templates/cluster.tf.template
scripts/terraform/templates/vars.tf.template
scripts/terraform/user-data.tpl

* Migrate to terraform 0.10.8
* Add resources specs for ASG
* Update user data for masters and nodes
* Add SSM integration
* Add design doc section

Add support for AWS auto scaling groups

---

scripts/terraform/asg.tf
scripts/terraform/envvars.tf

Keeps ASG instances in sync with other resources, tag wise
Tested out quickly using the following TF
```
provider "random" {
version = "~> 1.0"
}
provider "template" {
version = "~> 1.0"
}
locals {
common_tags = {
Terraform         = "true"
KubernetesCluster = "helgi"
Name              = "test"
}
}
// Create ASG tag setup from common tags
resource "null_resource" "asg_tags" {
count = "${length(local.common_tags)}"
triggers {
key                 = "${element(keys(local.common_tags), count.index)}",
value               = "${element(values(local.common_tags), count.index)}",
propagate_at_launch = true
}
}
locals {
asg_tags = ["${null_resource.asg_tags.*.triggers}"]
}
output "asg_tags" {
value = "${local.asg_tags}"
}
```
It outputs the following
```
👻  terraform apply …
```

Generate ASG tags based on common_tags

---

scripts/terraform/node-user-data.tpl

rename discover to autojoin

---

scripts/terraform/node-user-data.tpl

https://docs.aws.amazon.com/cli/latest/userguide/controlling-output.html#controlling-output-filter
I can keep the `2>&1` if desired.

use aws --query instead of awk to find the Value

---

scripts/terraform/iam.tf

This role doesn't appear to be used by anything anymore.

Remove unused S3 IAM role

---

Dockerfile
scripts/Makefile
scripts/scale-down.sh
scripts/scale-up.sh

Avoid using terraform to expand/shrink the cluster, as it may have unintended side effects, and just interact with the autoscaling group to add instances.

Switch to AWS commands to add/remove nodes

---

scripts/scale-up.sh

Remove some debugging I accidentally left in the scale-up script.

remove some debugging that was left in

---

Makefile
scripts/terraform/base.tf

https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md
https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#0113-january-31-2018

Bump TF and aws provide

---

scripts/terraform/base.tf

https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1110-march-09-2018

Bump aws TF provider to 1.11

---

Makefile

https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#0114-march-15-2018

Update terraform to 0.11.4

---

Makefile

no relevant fixes for us but I'd rather keep close sync
https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#0115-march-21-2018

Update to tf 0.11.5

---

scripts/terraform/node-user-data.tpl
scripts/terraform/user-data.tpl

Reverts gravitational/provisioner#36

Revert "Add explicit requirements setup for user scripts."

---

scripts/terraform/base.tf

https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1120-march-23-2018

Bump aws tf provider to 0.12

---

scripts/terraform/base.tf

https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1130-march-28-2018

Update aws tf provider to 1.13

---

Makefile

https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#0116-april-5-2018

Update to tf 0.11.6

---

scripts/terraform/base.tf

https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1140-april-06-2018

Bump aws tf provider to 1.14

---

scripts/terraform/base.tf

https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1150-april-18-2018

Update TF aws provider to 1.15

---

scripts/terraform/asg.tf

https://www.terraform.io/docs/providers/aws/r/launch_configuration.html#name_prefix

Create unique LCs with a prefix

---

scripts/terraform/base.tf

https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1160-april-25-2018

Update terraform aws provisioner to 1.16

---

scripts/terraform/base.tf

https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1170-may-02-2018
https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1180-may-10-2018
https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1190-may-16-2018
https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1200-may-23-2018

Update to TF aws provider v1.20

---

scripts/terraform/base.tf

https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1270-july-11-2018

Update TF aws provider to 1.29

---

scripts/terraform/base.tf

https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1380-september-26-2018

Bump aws provider to 1.38
